// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// import Link from "next/link";
// import "./globals.css";

// export const metadata = {
//   title: "Kazutora Hattori Portfolio",
//   description: "Developer & Designer in Vancouver",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="ja">
//       <body className="font-sans">
//         {/* ====== ナビゲーション ====== */}
//         <header className="flex justify-between items-center px-10 py-6">
//           {/* 左上ロゴ → Homeへ */}
//           <Link href="/" className="text-2xl font-bold">
//             KH
//           </Link>

//           {/* 右上 about ボタン */}
//           <nav>
//             <Link href="/about" className="text-lg hover:opacity-70">
//               about
//             </Link>
//           </nav>
//         </header>

//         {/* ---- 各ページの内容 ---- */}
//         <main className="px-10">{children}</main>
//       </body>
//     </html>
//   );
// }

import Link from "next/link";
import "./globals.css";
import { Noto_Sans_JP } from "next/font/google";
import { FaGithub, FaXTwitter } from "react-icons/fa6";

export const metadata = {
  title: "Kazutora Hattori Portfolio",
  description: "Developer & Designer in Vancouver",
};

const noto = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className={noto.className}>
      <body className="flex flex-col min-h-screen">

        {/* ====== Header ====== */}
        <header className="flex justify-between items-center px-10 py-6">
          <Link href="/" className="text-2xl font-bold">
            KH
          </Link>
          <nav>
            <Link href="/about" className="text-lg hover:opacity-70">
              about
            </Link>
          </nav>
        </header>

        {/* ====== Main (flex-grow で伸ばす) ====== */}
        <main className="px-10 flex-grow">{children}</main>

        {/* ====== Footer ====== */}
        <footer className="mt-20 py-10 text-center text-gray-600 space-y-4 bg-blue-100">
  <div className="flex justify-center gap-6 text-3xl">
    <a
      href="https://github.com/kazukashima"
      target="_blank"
      className="hover:opacity-70"
    >
      <FaGithub />
    </a>

    <a
      href="https://x.com/KazzTora1"
      target="_blank"
      className="hover:opacity-70"
    >
      <FaXTwitter />
    </a>
  </div>

  <p className="text-sm">© 2025 Kazutora Hattori</p>
</footer>

      </body>
    </html>
  );
}
